# Generated by Django 4.1.7 on 2023-03-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('ip_address', models.CharField(max_length=50)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.link')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='url_shortener.visitstatistics'),
        ),
    ]
